# Generated by Django 4.2.28 on 2026-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text="n8n session string like '123_168000000'", max_length=255, unique=True)),
                ('creator_id', models.CharField(help_text='User ID from Django frontend', max_length=255)),
                ('selected_video_id', models.CharField(help_text='The video_id from trending_videos the creator chose', max_length=255)),
                ('niche', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='script_generation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'creator_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('script_id', models.CharField(max_length=255, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('creator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('script_content', models.TextField()),
                ('script_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending_approval', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generated_scripts',
            },
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('creator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(max_length=1000)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending_approval', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generated_videos',
            },
        ),
        migrations.CreateModel(
            name='PostedVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('creator_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(max_length=1000)),
                ('tiktok_post_id', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posted_videos',
            },
        ),
        migrations.CreateModel(
            name='TrendingVideo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.IntegerField(help_text='The ID of the n8n scraping run')),
                ('rank', models.IntegerField()),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.CharField(blank=True, max_length=50, null=True)),
                ('likes', models.CharField(blank=True, max_length=50, null=True)),
                ('hashtags', models.JSONField(blank=True, help_text='Stored as an array/JSON in JS', null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('tiktok_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trending_videos',
                'ordering': ['-scraped_at', 'rank'],
            },
        ),
    ]
