# Generated by Django 4.2.28 on 2026-03-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedvideo',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trendingvideo',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Stored as string array by N8N', null=True),
        ),
    ]
