# Generated by Django 4.2.28 on 2026-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0002_alter_postedvideo_hashtags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPlatform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creator_id', models.CharField(help_text='User ID from Django frontend', max_length=255)),
                ('platform_name', models.CharField(default='tiktok', max_length=50)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('open_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_in', models.IntegerField(default=0, help_text='Seconds from when it was saved')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'connected_platforms',
                'unique_together': {('creator_id', 'platform_name')},
            },
        ),
    ]
