# Generated by Django 4.2.28 on 2026-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0003_connectedplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedvideo',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postedvideo',
            name='tiktok_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
