# Generated by Django 4.2.28 on 2026-03-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0004_postedvideo_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedvideo',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postedvideo',
            name='instagram_permalink',
            field=models.URLField(blank=True, help_text='Public Instagram URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='postedvideo',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postedvideo',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postedvideo',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postedvideo',
            name='video_url',
            field=models.URLField(help_text='Original media URL', max_length=1000),
        ),
    ]
