# Generated by Django 4.2.28 on 2026-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0005_postedvideo_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedvideo',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='postedvideo',
            name='instagram_media_id',
        ),
        migrations.RemoveField(
            model_name='postedvideo',
            name='instagram_permalink',
        ),
        migrations.RemoveField(
            model_name='postedvideo',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='postedvideo',
            name='shares_count',
        ),
        migrations.RemoveField(
            model_name='postedvideo',
            name='views_count',
        ),
        migrations.AddField(
            model_name='creatorsession',
            name='platform',
            field=models.CharField(default='tiktok', help_text='Platform: tiktok, instagram, facebook, youtube', max_length=50),
        ),
        migrations.AlterField(
            model_name='postedvideo',
            name='tiktok_post_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postedvideo',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
