# Generated by Django 4.2.28 on 2026-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0006_remove_postedvideo_comments_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(default='tiktok', max_length=50)),
                ('niche', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_runs',
            },
        ),
    ]
