# Generated by Django 4.2.28 on 2026-04-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0006_remove_postedvideo_comments_count_and_more'),
    ]

    operations = [
        # audio_url already added by n8n DB migration node - use RunSQL with IF NOT EXISTS
        migrations.RunSQL(
            sql="ALTER TABLE generated_videos ADD COLUMN IF NOT EXISTS audio_url VARCHAR(1000) NULL;",
            reverse_sql="ALTER TABLE generated_videos DROP COLUMN IF EXISTS audio_url;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE generated_videos ADD COLUMN IF NOT EXISTS is_fallback BOOLEAN NOT NULL DEFAULT FALSE;",
            reverse_sql="ALTER TABLE generated_videos DROP COLUMN IF EXISTS is_fallback;",
        ),
    ]
