# Generated by Django 4.2.28 on 2026-04-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0008_instagramreel'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsession',
            name='user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
