# Generated by Django 4.2.28 on 2026-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0008_facebookgeneratedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='cta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='hook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='hook_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='music_vibe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='negative_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='script_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookgeneratedvideo',
            name='video_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
