# Generated by Django 4.2.28 on 2026-05-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0015_add_thumbnail_url_to_facebookgeneratedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorsession',
            name='user_prompt',
        ),
    ]
