# Generated by Django 4.2.28 on 2026-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_integration', '0016_remove_creatorsession_user_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsession',
            name='user_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
