"""
AI Scripts app — model, serializer, views for generating and saving scripts.
Script generation returns a deterministic structured response (mocked AI).
In production, replace generate_script() with an OpenAI/Gemini API call.
"""
from django.db import models
from django.conf import settings


class AIScript(models.Model):
    """A user-generated AI content script."""

    STYLE_CHOICES = [
        ("Funny", "Funny"),
        ("Informative", "Informative"),
        ("Dramatic", "Dramatic"),
        ("Casual", "Casual"),
    ]
    DURATION_CHOICES = [
        ("30s", "30 seconds"),
        ("60s", "60 seconds"),
        ("90s", "90 seconds"),
    ]
    PLATFORM_CHOICES = [
        ("TikTok", "TikTok"),
        ("Instagram", "Instagram"),
        ("YouTube", "YouTube"),
        ("Facebook", "Facebook"),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="scripts")
    prompt = models.TextField()
    style = models.CharField(max_length=20, choices=STYLE_CHOICES, default="Informative")
    duration = models.CharField(max_length=5, choices=DURATION_CHOICES, default="60s")
    platform = models.CharField(max_length=20, choices=PLATFORM_CHOICES, default="TikTok")
    # Generated output
    hook = models.TextField(blank=True)
    script = models.TextField(blank=True)
    cta = models.TextField(blank=True)
    hashtags = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ai_scripts"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.user.email} — {self.prompt[:60]}"


class YouTubeVideo(models.Model):
    """
    Trending videos scraped by n8n.
    Managed by PostgreSQL/n8n directly.
    """
    video_id = models.CharField(max_length=100, unique=True)
    titre = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    vues = models.CharField(max_length=50)
    tags = models.TextField(blank=True, null=True)
    miniature = models.CharField(max_length=255, blank=True, null=True)
    niche = models.CharField(max_length=255)
    region = models.CharField(max_length=50, blank=True, null=True)
    scraped_at = models.DateTimeField()

    class Meta:
        db_table = "youtube_videos"
        ordering = ["-scraped_at"]

    def __str__(self):
        return f"[{self.niche}] {self.titre}"


class YouTubeGenerated(models.Model):
    """
    AI Content generated by n8n/Gemini.
    Managed by PostgreSQL/n8n directly.
    """
    user_id = models.IntegerField(null=True, blank=True)
    source_video_id = models.IntegerField(null=True, blank=True)
    niche = models.CharField(max_length=255)
    script = models.TextField()
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    tags = models.TextField(blank=True, null=True)
    video_url = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=50)  # pending_review, approved, rejected, posted
    youtube_video_id = models.CharField(max_length=100, blank=True, null=True)
    youtube_url = models.TextField(blank=True, null=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    posted_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()

    class Meta:
        db_table = "youtube_generated"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} - {self.status}"
