# Generated by Django 4.2.28 on 2026-02-27 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('X', 'X')], db_index=True, max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('growth', models.FloatField(default=0.0)),
                ('views', models.CharField(default='0', max_length=20)),
                ('type', models.CharField(choices=[('hashtag', 'Hashtag'), ('audio', 'Audio'), ('video', 'Video')], default='hashtag', max_length=10)),
                ('color_start', models.CharField(default='#6C5CE7', max_length=30)),
                ('color_end', models.CharField(default='#00C6FF', max_length=30)),
                ('analysis', models.JSONField(blank=True, default=list)),
                ('target_audience', models.CharField(default='General', max_length=100)),
                ('avg_video_length', models.CharField(default='30-60 seconds', max_length=50)),
                ('dominant_format', models.CharField(default='Entertainment', max_length=100)),
                ('best_posting_time', models.CharField(default='6-8 PM', max_length=50)),
                ('total_views', models.BigIntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('chart_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trends',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['platform'], name='trends_platfor_9d3bb3_idx'), models.Index(fields=['-score'], name='trends_score_30aa8f_idx'), models.Index(fields=['-growth'], name='trends_growth_fbff24_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savers', to='trends.trend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_trends',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'trend')},
            },
        ),
    ]
