# Generated by Django 4.2.28 on 2026-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel_id', models.TextField(unique=True)),
                ('reel_url', models.TextField(blank=True, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('niche', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='scraped')),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('created_db', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facebook_reels',
                'ordering': ['-play_count'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField(unique=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('vues', models.BigIntegerField(default=0)),
                ('niche', models.TextField(blank=True, null=True)),
                ('region', models.TextField(default='TN')),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube_videos',
                'ordering': ['-vues'],
                'managed': False,
            },
        ),
    ]
