from django.db import models
from django.conf import settings
import uuid

class TrendingVideo(models.Model):
    """Stores trending TikTok videos scraped by n8n daily (9AM trigger)"""
    id = models.BigAutoField(primary_key=True)
    run_id = models.IntegerField(help_text="The ID of the n8n scraping run")
    rank = models.IntegerField()
    video_id = models.CharField(max_length=255, unique=True)
    title = models.TextField(blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    views = models.CharField(max_length=50, blank=True, null=True)
    likes = models.CharField(max_length=50, blank=True, null=True)
    hashtags = models.TextField(blank=True, null=True, help_text="Stored as string array by N8N")
    category = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_url = models.URLField(max_length=1000, blank=True, null=True)
    tiktok_url = models.URLField(max_length=1000, blank=True, null=True)
    scraped_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "trending_videos"
        ordering = ["-scraped_at", "rank"]

    def __str__(self):
        return f"{self.rank}: {self.title} ({self.video_id})"


class CreatorSession(models.Model):
    """A workflow session triggered when the Creator chooses a trending video and niche"""
    id = models.BigAutoField(primary_key=True)
    session_id = models.CharField(max_length=255, unique=True, help_text="n8n session string like '123_168000000'")
    creator_id = models.CharField(max_length=255, help_text="User ID from Django frontend")
    selected_video_id = models.CharField(max_length=255, help_text="The video_id from trending_videos the creator chose")
    niche = models.CharField(max_length=255, blank=True, null=True)
    platform = models.CharField(max_length=50, default='tiktok', help_text="Platform: tiktok, instagram, facebook, youtube")
    status = models.CharField(max_length=100, default='script_generation')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "creator_sessions"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Session {self.session_id} - {self.niche}"


class GeneratedScript(models.Model):
    """The script generated by Ollama in n8n"""
    id = models.BigAutoField(primary_key=True)
    script_id = models.CharField(max_length=255, unique=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    script_content = models.TextField()
    script_json = models.JSONField(blank=True, null=True)
    status = models.CharField(max_length=50, default='pending_approval')
    feedback = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    declined_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "generated_scripts"

    def __str__(self):
        return self.script_id


class GeneratedVideo(models.Model):
    """The video generated by Fal.ai in n8n"""
    id = models.BigAutoField(primary_key=True)
    video_id = models.CharField(max_length=255, unique=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    video_url = models.URLField(max_length=1000)
    thumbnail_url = models.URLField(max_length=1000, blank=True, null=True)
    audio_url = models.URLField(max_length=1000, blank=True, null=True)
    prompt_used = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=50, default='pending_approval')
    feedback = models.TextField(blank=True, null=True)
    is_fallback = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    declined_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "generated_videos"

    def __str__(self):
        return self.video_id


class FacebookGeneratedVideo(models.Model):
    """Video generated by Facebook N8N workflow (Groq llama-3.3-70b)"""
    reel_id = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    niche = models.CharField(max_length=255, blank=True, null=True)
    user_prompt = models.TextField(blank=True, null=True)

    # Full Groq-generated script (hook + body + cta joined)
    script_content = models.TextField(blank=True, null=True)
    # Raw script JSON from Groq
    script = models.JSONField(blank=True, null=True)
    script_text = models.TextField(blank=True, null=True)  # kept for backward compat

    # Script parts (displayed individually in the app)
    hook = models.TextField(blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    cta = models.TextField(blank=True, null=True)

    # Video generation fields
    hook_text = models.TextField(blank=True, null=True)
    video_prompt = models.TextField(blank=True, null=True)
    negative_prompt = models.TextField(blank=True, null=True)
    caption = models.TextField(blank=True, null=True)
    hashtags = models.TextField(blank=True, null=True)
    music_vibe = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)

    video_url = models.URLField(max_length=1000, blank=True, null=True)
    thumbnail_url = models.URLField(max_length=1000, blank=True, null=True)
    status = models.CharField(max_length=50, default='processing')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "facebook_generated_videos"

    def __str__(self):
        return f"{self.reel_id} - {self.niche} - {self.status}"


class PostedVideo(models.Model):
    """Final posted video on TikTok by n8n"""
    id = models.BigAutoField(primary_key=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    video_url = models.URLField(max_length=1000)
    tiktok_post_id = models.CharField(max_length=255)
    caption = models.TextField(blank=True, null=True)
    hashtags = models.TextField(blank=True, null=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "posted_videos"

    def __str__(self):
        return self.tiktok_post_id


class ConnectedPlatform(models.Model):
    """Stores OAuth tokens for platforms connected directly by the user"""
    id = models.BigAutoField(primary_key=True)
    creator_id = models.CharField(max_length=255, help_text="User ID from Django frontend")
    platform_name = models.CharField(max_length=50, default="tiktok")
    
    # OAuth tokens
    access_token = models.CharField(max_length=500)
    refresh_token = models.CharField(max_length=500, blank=True, null=True)
    open_id = models.CharField(max_length=255, blank=True, null=True)
    expires_in = models.IntegerField(default=0, help_text="Seconds from when it was saved")
    
    # Audit
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "connected_platforms"
        unique_together = ('creator_id', 'platform_name')

    def __str__(self):
        return f"{self.creator_id} - {self.platform_name}"
