from django.db import models
from django.conf import settings
import uuid

class WorkflowRun(models.Model):
    """Tracks a single execution of a scraping workflow (n8n or direct)"""
    id = models.BigAutoField(primary_key=True)
    platform = models.CharField(max_length=50, default='tiktok')
    niche = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=50, default='running')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "workflow_runs"

    def __str__(self):
        return f"Run {self.id} - {self.platform} ({self.niche})"

class TrendingVideo(models.Model):
    """Stores trending TikTok videos scraped by n8n daily (9AM trigger)"""
    id = models.BigAutoField(primary_key=True)
    run_id = models.IntegerField(help_text="The ID of the n8n scraping run")
    rank = models.IntegerField()
    video_id = models.CharField(max_length=255, unique=True)
    title = models.TextField(blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    views = models.CharField(max_length=50, blank=True, null=True)
    likes = models.CharField(max_length=50, blank=True, null=True)
    hashtags = models.TextField(blank=True, null=True, help_text="Stored as string array by N8N")
    category = models.CharField(max_length=100, blank=True, null=True)
    thumbnail_url = models.URLField(max_length=1000, blank=True, null=True)
    tiktok_url = models.URLField(max_length=1000, blank=True, null=True)
    scraped_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "trending_videos"
        ordering = ["-scraped_at", "rank"]

    def __str__(self):
        return f"{self.rank}: {self.title} ({self.video_id})"


class CreatorSession(models.Model):
    """A workflow session triggered when the Creator chooses a trending video and niche"""
    id = models.BigAutoField(primary_key=True)
    session_id = models.CharField(max_length=255, unique=True, help_text="n8n session string like '123_168000000'")
    creator_id = models.CharField(max_length=255, help_text="User ID from Django frontend")
    selected_video_id = models.CharField(max_length=255, help_text="The video_id from trending_videos the creator chose")
    niche = models.CharField(max_length=255, blank=True, null=True)
    platform = models.CharField(max_length=50, default='tiktok', help_text="Platform: tiktok, instagram, facebook, youtube")
    status = models.CharField(max_length=100, default='script_generation')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "creator_sessions"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Session {self.session_id} - {self.niche}"


class GeneratedScript(models.Model):
    """The script generated by Ollama in n8n"""
    id = models.BigAutoField(primary_key=True)
    script_id = models.CharField(max_length=255, unique=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    script_content = models.TextField()
    script_json = models.JSONField(blank=True, null=True)
    status = models.CharField(max_length=50, default='pending_approval')
    feedback = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    declined_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "generated_scripts"

    def __str__(self):
        return self.script_id


class GeneratedVideo(models.Model):
    """The video generated by Fal.ai in n8n"""
    id = models.BigAutoField(primary_key=True)
    video_id = models.CharField(max_length=255, unique=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    video_url = models.URLField(max_length=1000)
    prompt_used = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=50, default='pending_approval')
    feedback = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(blank=True, null=True)
    declined_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = "generated_videos"

    def __str__(self):
        return self.video_id


class PostedVideo(models.Model):
    """Final posted video on TikTok by n8n"""
    id = models.BigAutoField(primary_key=True)
    session_id = models.CharField(max_length=255)
    creator_id = models.CharField(max_length=255, blank=True, null=True)
    video_url = models.URLField(max_length=1000)
    tiktok_post_id = models.CharField(max_length=255)
    caption = models.TextField(blank=True, null=True)
    hashtags = models.TextField(blank=True, null=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "posted_videos"

    def __str__(self):
        return self.tiktok_post_id


class ConnectedPlatform(models.Model):
    """Stores OAuth tokens for platforms connected directly by the user"""
    id = models.BigAutoField(primary_key=True)
    creator_id = models.CharField(max_length=255, help_text="User ID from Django frontend")
    platform_name = models.CharField(max_length=50, default="tiktok")
    
    # OAuth tokens
    access_token = models.CharField(max_length=500)
    refresh_token = models.CharField(max_length=500, blank=True, null=True)
    open_id = models.CharField(max_length=255, blank=True, null=True)
    expires_in = models.IntegerField(default=0, help_text="Seconds from when it was saved")
    
    # Audit
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "connected_platforms"
        unique_together = ('creator_id', 'platform_name')

    def __str__(self):
        return f"{self.creator_id} - {self.platform_name}"


class InstagramReel(models.Model):
    """
    Maps to the instagram_reels table populated by the N8N Instagram scraping workflow.
    managed=False: Django won\'t touch the schema — N8N upserts handle it.
    """
    reel_id = models.TextField(unique=True)          # Instagram shortCode
    reel_url = models.TextField(null=True, blank=True)  # https://www.instagram.com/reels/<shortCode>/
    thumbnail_url = models.TextField(null=True, blank=True)
    caption = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)  # @username
    views = models.BigIntegerField(default=0)
    likes = models.BigIntegerField(default=0)
    niche = models.TextField(null=True, blank=True)   # niche tag used when triggered
    hashtags = models.TextField(null=True, blank=True)  # raw PostgreSQL array string
    scraped_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = "instagram_reels"
        ordering = ["-scraped_at", "-views"]

    def __str__(self):
        return f"{self.niche} - {self.reel_id}"
