# Generated by Django 4.2.28 on 2026-02-27 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('style', models.CharField(choices=[('Funny', 'Funny'), ('Informative', 'Informative'), ('Dramatic', 'Dramatic'), ('Casual', 'Casual')], default='Informative', max_length=20)),
                ('duration', models.CharField(choices=[('30s', '30 seconds'), ('60s', '60 seconds'), ('90s', '90 seconds')], default='60s', max_length=5)),
                ('platform', models.CharField(choices=[('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook')], default='TikTok', max_length=20)),
                ('hook', models.TextField(blank=True)),
                ('script', models.TextField(blank=True)),
                ('cta', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_scripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
