# Generated by Django 4.2.28 on 2026-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('source_video_id', models.IntegerField(blank=True, null=True)),
                ('niche', models.CharField(max_length=255)),
                ('script', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_url', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'youtube_generated',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('vues', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True, null=True)),
                ('miniature', models.CharField(blank=True, max_length=255, null=True)),
                ('niche', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'youtube_videos',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
