# Generated by Django 4.2.28 on 2026-02-27 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(choices=[('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('X', 'X')], max_length=20)),
                ('connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_platforms',
                'unique_together': {('user', 'platform_name')},
            },
        ),
    ]
