# Generated by Django 6.0.3 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplatform',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplatform',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
